version: '3'
services:
  app:
    container_name: 'NidGuayAPI'
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - DATABASE_HOST=postgres
      - DATABASE_NAME=nidguay
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=qwerty
      - DATABASE_PORT=5432
      - SECRET_KEY=ComputerEngineering
      - NODE_ENV=development
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nidguay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
