apiVersion: v1
kind: PersistentVolume
metadata:
  name: nidguay-pv-volume
  namespace: nidguay
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s"
